### ISSUE TITLE
Redisの設定が行えるAnsibleの設定を作る

### ISSUE THREAD

**Issue by h5y1m141** [h5y1m141/life_with_beer#61]
## このIssueについて

Vagrant環境に対してRedisのインストールが行えるAnsibleの設定を作ってもらいたいと思います

Redisの設定ファイルは特別必要としないと思うので、Nginxのインストール用のAnsibleの以下設定を参考に作業してもらえればOKかと思います

```yaml
---
- name: check if repository registerd
  shell: bash -c 'yum repolist all | grep nginx/x86_64'
  register: result
  failed_when: result.rc not in [0, 1]
  tags: nginx  
- name: add nginx repository
  yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm state=present
  when: result.rc == 1
  tags: nginx  
- name: install nginx
  yum: name=nginx state=installed
  tags: nginx
- name: start nginx
  shell: bash -c 'systemctl enable nginx; systemctl start nginx'

```
